return {
--   {
--     "nvim-treesitter/nvim-treesitter",
--     build = ":TSUpdate",
--     dependencies = {
--       "nvim-treesitter/nvim-treesitter-textobjects",
--       { "windwp/nvim-ts-autotag", config = true },
--       { "PriceHiller/nvim-treesitter-endwise", branch = "fix/iter-matches" },
--       {
--         "windwp/nvim-autopairs",
--         opts = {
--           close_triple_quotes = true,
--           check_ts = true,
--           enable_moveright = true,
--           fast_wrap = { map = "<c-e>" },
--         },
--         config = function(_, opts)
--           local autopairs = require("nvim-autopairs")
--           autopairs.setup(opts)
--           local Rule = require("nvim-autopairs.rule")
--           local ts_conds = require("nvim-autopairs.ts-conds")
--           autopairs.add_rules({
--             Rule("{{", "  }", "vue"):set_end_pair_length(2):with_pair(ts_conds.is_ts_node("text")),
--           })
--         end,
--       },
--       { "abecodes/tabout.nvim", opts = { tabkey = "<Tab>", backwards_tabkey = "<S-Tab>", completion = true } },
--     },
--     config = function()
--       require("nvim-treesitter.configs").setup({
--         ensure_installed = "all",
--         ignore_install = { "phpdoc", "norg" },
--         highlight = {
--           enable = true,
--           disable = function(lang, bufnr)
--             return vim.bo[bufnr].filetype == "eruby"  -- Disable for html.erb
--           end,
--         },
--         indent = {
--           enable = true,
--           disable = function(lang, bufnr)
--             return vim.bo[bufnr].filetype == "eruby"
--           end,
--         },
--         injection = {
--           enable = true,
--           disable = function(lang, bufnr)
--             return vim.bo[bufnr].filetype == "eruby"
--           end,
--         },
--         incremental_selection = {
--           enable = true,
--           keymaps = {
--             init_selection = "<M-w>",
--             scope_incremental = "<CR>",
--             node_incremental = "<Tab>",
--             node_decremental = "<S-Tab>",
--           },
--         },
--         endwise = { enable = false },
--         textobjects = {
--           select = {
--             enable = true,
--             lookahead = true,
--             keymaps = {
--               ["af"] = "@function.outer",
--               ["if"] = "@function.inner",
--               ["ac"] = "@class.outer",
--             },
--           },
--         },
--         markdown = { enable = true },
--         markdown_inline = { enable = true },
--       })
--     end,
--   },
}
