# Setup paths
export ZSH=$HOME/.dotfiles/zsh
source $ZSH/exports.zsh

# use .localrc for SUPER SECRET CRAP that you don't want in your public, versioned repo.
source ~/.localrc

# Import additional .zsh files
source $ZSH/config.zsh
source $ZSH/prompt.zsh
source $ZSH/aliases.zsh

# Plugins
source $ZSH/plugins/base16.zsh
source $ZSH/plugins/cg.zsh
source $ZSH/plugins/fzf.zsh
source $ZSH/plugins/node.zsh
source $ZSH/plugins/rbenv.zsh

# External Plugins
fpath=(/usr/local/share/zsh-completions $fpath)

# Functions
fpath=($ZSH/functions $fpath)
autoload -U $ZSH/functions/c(:t)
autoload -U $ZSH/functions/smartextract(:t)

# Used to profile ZSH loading speed
# > for i in $(seq 1 10); do /usr/bin/time /bin/zsh -i -c exit; done;
zmodload zsh/zprof

# initialize autocomplete here, otherwise functions won't be loaded
autoload -Uz compinit
if [[ -n ${ZDOTDIR}/.zcompdump(#qN.mh+24) ]]; then
	compinit;
else
	compinit -C;
fi;
